spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb+srv://aarushiyadav231_db_user:Arushi123@cluster0.esu6wdh.mongodb.net/journaldb
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: aarushiyadav231@gmail.com
    password: ojit mltw dwsv adwj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: ac655909e4fa0d52bb12e2e82eceb9e5

