
spring:
  data:
    mongodb:
      uri: mongodb+srv://aarushiyadav231_db_user:Arushi123@cluster0.esu6wdh.mongodb.net/journaldb
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal